server:
  port: 8101

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.73.234:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: test
    password: test
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

dubbo:
  protocol:
    id: dubbo
    name: dubbo
    port: 10005
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
  registry:
    id: ${spring.application.name}-registry
    address: zookeeper://127.0.0.1:2181
    check: false
  consumer:
    check: false


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.example.service.*.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.service.*.entity